### ISSUE TITLE
Correctly parse / unparse `undefined` value in shorthand

### ISSUE THREAD

**Issue by felixcodes** [vega/compassql#265]
We currently use JSON.stringify to shorthand enum values. Stringify converts undefined to null, however, and we should be able to parse back undefined when appropriate (ex. scale = undefined is totally valid).

**Comment by kanitw** [comment]
I don't think describes the problem well.  

`{scale: undefined}`  and `{}` renders the same thing.

The problem is 

`{aggregate: {enum: [undefined, 'min']}}` will become `{aggregate: {enum: [null, 'min']}}` when stringified.   

For aggregate, this is okay.  For scale, axis, legend, this **might** cause problem. 
I can't remember if we do `{scale: {enum: [false, true]}}` or `{scale: {enum: [null, undefined]}}` though.  The former would be okay, the latter would be problematic as `undefined` can be come `null`.   (This case should be extremely rare though!)

**Comment by kanitw** [comment]
We do `{scale: {enum: [false, true]}}`  so this is not a problem.
