### ISSUE TITLE
How the "effectiveness" ranking is build?

### ISSUE THREAD

**Issue by lavsurgut** [vega/compassql#368]
It would be great if you can provide an intuition behind your explicit ranking system in the compassql implementation. For example, in the typechannel score:

    const CONTINUOUS_TYPE_CHANNEL_SCORE = {
      x: 0,
      y: 0,
      size: -0.575,
      color: -0.725,  // Middle between -0.7 and -0.75
      text: -2,
      opacity: -3,

      shape: TERRIBLE,
      row: TERRIBLE,
      column: TERRIBLE,
      detail: 2 * TERRIBLE
    };

What is the reason to use -0.575 and -0.725, but not some other numbers? 

Thank you very much in advance.

**Comment by kanitw** [comment]
Thanks for asking!

These numbers are based on solving a linear programming that encodes constraints for our ranking.  0.725 can actually be 0.724 or 0.726, or any other number as long as they satisfy the set of ranking constraints we have (we also list these constraints in the automated test).  

We pick 0.725 simply because it's a nice number between -0.7 and -0.75.

We might add more constraints to the ranking in the future and these numbers might change (for a good reason).
